name: MountMayhem
main: no.runsafe.mountmayhem.Plugin
version: 1.0.@BUILD@
author: Kruithne
description: Mounting
commands:
  mount:
    description: Mounting
    usage: /mount <player> <player>
    permission: mountmayhem.mount
  dismount:
    description: Makes the player dismount
    usage: /dismount <player>
    permission: mountmayhem.dismount