name: MountMayhem
main: no.runsafe.mountmayhem.Plugin
version: 1.0.@BUILD@
author: Kruithne
description: Mounting
commands:
  mount:
    description: Mounting
  dismount:
    description: Makes the player dismount
